app = "production-deployment-test"
primary_region = "arn"
org = "wacoco"

[build]
dockerfile = "Dockerfile"

[env]
SERVER_PORT = "8080"
SPRING_PROFILES_ACTIVE = "prod"

[[services]]
internal_port        = 8080
protocol             = "tcp"
auto_stop_machines   = "stop"
auto_start_machines  = true
min_machines_running = 1

[[services.ports]]
port     = 80
handlers = ["http"]

[[services.ports]]
port     = 443
handlers = ["tls", "http"]

[[services.tcp_checks]]
grace_period = "1s"
interval     = "15s"
timeout      = "10s"
restart_limit= 0

[vm]
cpu_kind  = "shared"
cpus      = 1
memory_mb = 256

[metrics]
port = 8080
path = "/actuator/prometheus"